### ISSUE TITLE
[FEATURE] Footer for users to connect to your app on social media / email / contact number and contact with you

### ISSUE THREAD

**Issue by Adeesh-bode** [krishnaacharyaa/wanderlust#196] opened 2024-05-11 19:24 UTC
### Description

This feature involves adding a footer section to your application or website that includes links or contact details for social media platforms, email, and a contact number. The purpose of the footer is to provide users with easy access to multiple channels for connecting with your organization or business. This not only enhances the user experience by offering convenience but also helps in building stronger relationships with users through improved communication.

### Use Case

Consider a small business website that aims to expand its online presence and customer interaction. By integrating a footer with direct links to their social media profiles, an email address, and a contact number, the business makes it straightforward for visitors to follow their social media channels, make inquiries, or provide feedback. This easy accessibility encourages users to engage more deeply with the brand, whether to follow updates, participate in community discussions, or reach out for customer support. The footer serves as a constant, visible invitation for communication, regardless of which page the user is on, thus facilitating better connectivity and engagement with the audience.

**Comment by krishnaacharyaa** [comment] 2024-05-12 03:23
@Adeesh-bode Kindly find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)

**Comment by itspsycho07** [comment] 2024-05-12 06:07
Please assign me the issue

**Comment by krishnaacharyaa** [comment] 2024-05-12 06:09
@itspsycho07 take a moment, give it some time and read [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share). :)

**Comment by Tarungupta18** [comment] 2024-05-12 15:33
please assign me the issue

**Comment by krishnaacharyaa** [comment] 2024-05-12 17:03
@Tarungupta18  take a moment, give it some time and read [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share). :)

Closing it as it isn't clear of what the issue is about

**Closed by krishnaacharyaa** 2024-05-12 17:03 UTC
Labels: feature

**Comment by bikashsahh** [comment] 2024-05-12 17:06
I can help with this feature. Kindly assign me this issue.
