### ISSUE TITLE
[BUG] Issue in Latest Post Section

### ISSUE THREAD

**Issue by Raghunandan-29** [krishnaacharyaa/wanderlust#93] opened 2023-12-28 08:54 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Array of 16 post are fetching from this api "https://wanderlust-backend-bay.vercel.app/api/posts/latest" for latest section, out of these 16 only first 5 posts are rendering.This array is not sorted correctly, this is because of issue in the database I guess. Most of the sample posts are taking system date and time as a time of Post, may be this is causing the issue. In local api for this latest post also same issue newly created posts are sorted correctly in the response, but the sample posts which are in db initially are taking system date and time as timeOfPost they are not sorted in the response of api. This is same with the api  "https://wanderlust-backend-bay.vercel.app/api/posts/latest"

<img width="1436" alt="Screenshot 2023-12-27 at 10 21 24 PM" src="https://github.com/krishnaacharyaa/wanderlust/assets/102844162/292c766e-8d8a-4f3a-a1b0-cd75c8db5910">

### Expected Behavior

Response from the api "https://wanderlust-backend-bay.vercel.app/api/posts/latest" should be sorted correctly by the date and time of Post.

### Reproduction URL

https://github.com/Raghunandan-29

### Reproduction steps

```bash
1. Go to 'https://wanderlust-beta.vercel.app/'
2. Checkout 'Latest Posts'
3. Scroll down to 'All Posts'
4. There are many Posts with latest date and time than the posts rendered in the Latest Posts section.
5. See error

For Api:
1. Go to 'https://wanderlust-backend-bay.vercel.app/api/posts/latest'
2. Check the response timeOfPost (they are not sorted correctly)
3. The post which are added by create post are sorted corrctly but the sample post in DB are not sorted.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by soheb-btw** [comment] 2024-03-20 17:27
@krishnaacharyaa can I take this issue ?

**Comment by krishnaacharyaa** [comment] 2024-03-20 23:57
@soheb-btw sure 
Assigning it to you
Please let us know the time estimation to complete the task

**Comment by soheb-btw** [comment] 2024-03-21 15:17
@krishnaacharyaa I am unable to run recreate the bug on local, sorting seems to be fine on local.
while going through the code I have seen that all the posts that didn't had timeOfPost values in db would give you current time and date when api/posts is called.

![git](https://github.com/krishnaacharyaa/wanderlust/assets/59690289/c48d21f8-4f03-4ca6-b6f7-366317342873)

**Comment by soheb-btw** [comment] 2024-03-21 15:19
Are there any post in db that don't have timeOfPost value ?

**Comment by krishnaacharyaa** [comment] 2024-03-21 16:17
Good catch @soheb-btw , I suspect the problem is with the initial db values which is sample data.json from the readme file ....(ref)
Youu would may be able to reproduce there, if not .... Let me know I'll send the original db's json content....

I suspect that's the issue because I don't see timeofPost value in the sample data

**Comment by soheb-btw** [comment] 2024-03-21 16:50
I did import data from sample_posts.json while setting up the project and then removed all data for testing, both cases I was facing the date issue.

It will be great if you can send the original db's json and then I can debug further and we can know for sure.

**Comment by krishnaacharyaa** [comment] 2024-03-21 18:00
Sure, tomorrow I'll send , please remind me if I forget, either here or in discord, tag master

**Comment by krishnaacharyaa** [comment] 2024-03-22 06:43
Hi @soheb-btw, Please use this for reference, straight from the db 
[wanderlust.posts.json](https://github.com/krishnaacharyaa/wanderlust/files/14718528/wanderlust.posts.json)

**Comment by soheb-btw** [comment] 2024-03-23 05:39
Hi @krishnaacharyaa missing timeOfPost values are creating the issue. It cannot be empty

**Comment by krishnaacharyaa** [comment] 2024-03-23 05:47
Sure @soheb-btw, thank you for the root cause. So were all do we have to change I guess the sample data and the db data right?

**Comment by soheb-btw** [comment] 2024-03-23 05:54
yes, we need add missing timeOfPost values in both files.

**Comment by soheb-btw** [comment] 2024-03-23 05:54
yes, we need add missing timeOfPost values in both files.

**Comment by soheb-btw** [comment] 2024-03-23 05:58
And one more change is required in /api/posts route, Assuming in All Posts section we are showing latest posts first, its sorting logic is not implemented for the route. I have made the code changes can I make a pull request for this ?

**Comment by krishnaacharyaa** [comment] 2024-03-23 06:16
Sure, can you please follow the contributing guidelines and raise PR. @soheb-btw

**Comment by soheb-btw** [comment] 2024-03-23 09:12
@krishnaacharyaa I have created the pull request from a different account.

**Comment by krishnaacharyaa** [comment] 2024-03-23 10:42
@soheb-btw I have addressed the PR, kindly make the changes and let me know

**Closed** 2024-03-23 17:10 UTC
Labels: bug
