### ISSUE TITLE
[ENHANCEMENT] Enhancing Footer of website to make it more informative and structured.

### ISSUE THREAD

**Issue by EshaalakshmiDS** [krishnaacharyaa/wanderlust#403] opened 2024-06-06 07:12 UTC
### Description

 A well-designed footer can significantly improve visitor retention and effectively guide them to other parts of the website. This makes it vital to ensure that footer is easily accessible, user-friendly, and informative. I would like to contribute to improve the existing footer with links, contact details and social media icons. I request you to please assign me this under GSSOC'24 label.

### Current Behavior

The current footer only displays the "2024 All Rights Reserved along with label wanderlust. 
I feel that it fails to leave an impression on the website visitor. It also isn't functional as it misses to display important information like contact details, like social media platforms etc.   
![wanderlust](https://github.com/krishnaacharyaa/wanderlust/assets/97681609/19954757-6b21-46de-8ffa-6c2853e48702)

### Proposed Enhancement

1. Menu items to discover more about the company and its products or services. 
2. Name, address, and phone number: These details directly impact your local SEO efforts, and need to be present and accurate. 
3. Email address: Provide an email address where potential clients can contact you. 
4. Social media icons: Social links can help you increase engagement. 
![wanderlust (2)](https://github.com/krishnaacharyaa/wanderlust/assets/97681609/e29dfa48-65ef-4b0c-bc63-4da0eaf87bab)

### Use Case

The website footer is excellent for keeping people on-site once they’ve reached the bottom of a page. Website footer should be well-structured and ensure easy navigation. The goal is to ensure your visitors can effortlessly find everything they need without having to scroll all the way back up to the top – or they might lose interest.

**Comment by EshaalakshmiDS** [comment] 2024-06-06 07:16
@krishnaacharyaa I request you to please review this issue, and assign it to me under GSSOC'24. I will work deligently on this and make sure to submit a PR once done. Thank you so much.

**Comment by officeneerajsaini** [comment] 2024-06-07 10:35
#401

**Comment by krishnaacharyaa** [comment] 2024-06-18 01:22
Duplicate of https://github.com/krishnaacharyaa/wanderlust/issues/379

**Closed by krishnaacharyaa** 2024-06-18 01:22 UTC
Labels: enhancement
