### ISSUE TITLE
Adding the Social Media Icons To Footer

### ISSUE THREAD

**Issue by narayani9120** [krishnaacharyaa/wanderlust#400] opened 2024-06-04 17:59 UTC
### Description

Adding social media icons to the footer of a website offers benefits for User.
Social media icons can drive traffic to the website's social media profiles, increasing the potential for user engagement and interaction. Users can quickly find and follow the website's social media profiles without having to search for them manually.

### Current Behavior

![image](https://github.com/krishnaacharyaa/wanderlust/assets/125353066/93c20150-53b9-479a-943c-bf50f889d3c1)

### Proposed Enhancement

Excepted :
![image](https://github.com/krishnaacharyaa/wanderlust/assets/125353066/1f61a148-9709-48c2-b54e-2929e461e918)

### Use Case

Users can engage with the brand more easily through likes, comments, shares, and direct messages on social media platforms.By encouraging visitors to follow their social media profiles, website owners can grow their audience base and reach a broader audience.

### Additional Information/ Attachment

Assign this issues under gssoc

**Comment by krishnaacharyaa** [comment] 2024-06-18 01:24
Duplicate of https://github.com/krishnaacharyaa/wanderlust/issues/379

**Closed by krishnaacharyaa** 2024-06-18 01:24 UTC
Labels: enhancement
