### ISSUE TITLE
[ENHANCEMENT] Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [krishnaacharyaa/wanderlust#208] opened 2024-05-13 02:39 UTC
### Description

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

### Current Behavior

Currently, no automated messages are there. The users have to add messages manually.

### Proposed Enhancement

Post enhancements will look like this.
![image](https://github.com/krishnaacharyaa/wanderlust/assets/50082154/615e1fea-50ec-4e70-8ccd-a5548d1100fc)

### Use Case

Saves Time and makes the contributors feel appreciated.

**Comment by krishnaacharyaa** [comment] 2024-05-13 07:49
Hi @sanmarg , that is interesting, but if you are spaming going at all the projects with same issue, then not the place for you.
But if you are genuinuely interested we can take this up with some modifications.

Like when PR is created, i want to know if somethings are followed ... and want some checks and automation, if you can take that after some research that would be really appreciated, i can give highest points available in the gssoc if you come up with the solution and you are actually interested

**Comment by sanmarg** [comment] 2024-05-13 17:42
I am writing this because I am genuinely interested in contributing to the open source. I'm not spamming, I found a thing that could be added to the project so I made an issue. 
I will surely research about the checks and I am looking forward to work on this.

**Comment by krishnaacharyaa** [comment] 2024-05-13 17:46
Okay I'll give you benefit of doubt, Thanks for the idea, I'm looking forward for these

1. As soon as issue is created, it should say "Hi , hope you have followed the code of conduct, if it doesn't follow we'll close this issue" and additionally it should also ai generation checks if possible
2. As soon as the issue is assigned, it should give link of the contributing guidelines and ask them to follow it
3. As soon as the PR is raised, it should check the PR content see some regex basically our format and check the commits for the community guidelines and prompt saying you have not followed the code guidelines bla bla
Something around this, i know this will be challenging, but this will be really interesting issue if we can come up with a solution.

Please sync with @Mayur-666 Both together, sync up and take this up. This is the need now, the much better we are able to do this, better it is for us.
Let me know how it works out for both of you @sanmarg @Mayur-666

**Comment by sanmarg** [comment] 2024-05-13 17:53
Sure, Sir.

**Comment by krishnaacharyaa** [comment] 2024-05-13 18:01
@sanmarg can you create the first issue for now and work on it? we'll split this into 4 issues, so that you get good number of points :)
4th one being the AI part, we'll exclude the ai feature from the first one for now...
Can you start working on the 1st one? and raise PR following the guidelines!?

cc: @Mayur-666

**Comment by sanmarg** [comment] 2024-05-13 18:24
Sure, I'll get started on creating the first issue and working on it. Thank you for breaking down the tasks and providing clear instructions!

**Comment by krishnaacharyaa** [comment] 2024-05-13 18:26
Super @sanmarg

**Comment by Mayur-666** [comment] 2024-05-14 03:16
Sure thing! I sleep early, that's why didn't able to reply, starting the research soon @krishnaacharyaa .

**Comment by krishnaacharyaa** [comment] 2024-05-14 03:33
@Mayur-666 yeah i have tagged you in the issue, kindly look into it

**Comment by Mayur-666** [comment] 2024-05-14 04:02
I have one template for the greeting.yaml file, 
It should do these thing :-
 -  issue-message: 'Congratulations, @${{ github.actor }}! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!'
  
 - pr-message: 'Great job, @${{ github.actor }}! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.'
     
  -  footer: 'We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/pull_request_template.md) or (https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md)' based on the issue or PR

**Comment by krishnaacharyaa** [comment] 2024-05-14 04:06
Yeah @Mayur-666 you can add these as well, but right now it is not of much concern, it might be added as bonus for points may be if required. This is the need for now https://github.com/krishnaacharyaa/wanderlust/issues/230

**Comment by Mayur-666** [comment] 2024-05-14 04:25
I thinks the checks for pr and issues can be done in two ways -
1. Make a special regex for the checks.
2. send the format and actual content to api with curl command to check them.

So i want that these messages should be the first step, then we can proceed with the ai check as they'll require testing.

**Comment by Mayur-666** [comment] 2024-05-14 04:33
Ok then in this issue i'll work on adding message and testing them in my repos, rest will take care in others. @krishnaacharyaa  will it be ok

**Comment by krishnaacharyaa** [comment] 2024-05-14 04:38
> @krishnaacharyaa I thinks the checks for pr and issues can be done in two ways -
> 
> 1. Make a special regex for the checks.
> 2. send the format and actual content to api with curl command to check them.
> 
> So i want that these messages should be the first step, then we can proceed with the ai check as they'll require testing.

I didn't totally get you, but yeah i guess the acceptance criteria is clear enough, take it one by one, I am open to the approach you have, I have pinged in the closed PR aswell, look there, lets from now have conversation in #230 , too many places currently

**Comment by Mayur-666** [comment] 2024-05-18 23:53
I see the work has already been done. Nice !

**Closed** 2024-05-28 18:13 UTC
Labels: enhancement
