### ISSUE TITLE
[ENHANCEMENT] Enhance Footer

### ISSUE THREAD

**Issue by Hemashree21** [krishnaacharyaa/wanderlust#401] opened 2024-06-05 15:21 UTC
### Description

I want to work on enhancing the Footer.

### Current Behavior

The current Footer just has a copyright and Logo. 

### Proposed Enhancement

I want to add links to different pages like About or Contact and also add some social media icons. I will also ensure that it's responsive.

### Use Case

It's beneficial for easy access to different pages once the user scrolls down and also to engage with the users through different social media accounts as well.

### Additional Information/ Attachments

![Screenshot 2024-05-16 092104](https://github.com/krishnaacharyaa/wanderlust/assets/138188163/f50ca99c-848c-43a6-92b9-17a61a7643d1)

@krishnaacharyaa can you please assign this to me?

**Comment by krishnaacharyaa** [comment] 2024-06-18 01:23
Duplicate of https://github.com/krishnaacharyaa/wanderlust/issues/379

**Closed by krishnaacharyaa** 2024-06-18 01:23 UTC
Labels: enhancement
